### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by pranavbhattad** [Vedant404ButFound/Simple-Python-Projects#1]
Who the hell are you first tell me and why are you spamming my repo I have just made it Public for my friends not for you I don't want to report you on Github

**Comment by Vedant404ButFound** [comment]
Sorry,Bro I am also Big Fan Of Harry Sir I saw his code so I fell bad and I said 'COPY' BTW Your Coading Skill Is So Nice.
In My Birthday-Wish.py I improved with **pywhatkit** and **create_xlsx** function And In My Password-Genrator.py I improved with less lines of code.
# Once Again Sorry
