### ISSUE TITLE
An yes. 

### ISSUE THREAD

**Issue by pranavbhattad** [Vedant404ButFound/Simple-Python-Projects#2]
the name of the file is his.py now I have changed it cwh.py I had taken it for reference. If you should have commented then you should have commented on main.py. And what else I have copied my Voice Assistant is better than his. The faulty calculator was a  practice given by him. He is like my teacher and if he doesn't have a problem then who the hell you are. My other projects are done by myself. The birthday wisher is his copy and even password generator even you are a copycat. I downloaded your pyved python package I should not comment anything coz I don't want to be like you

**Comment by Vedant404ButFound** [comment]
Sorry,Bro I am also Big Fan Of Harry Sir I saw his code so I fell bad and I said 'COPY' BTW Your Coading Skill Is So Nice.
In My Birthday-Wish.py I improved with **pywhatkit** and **create_xlsx** function And In My Password-Genrator.py I improved with less lines of code.
# Once Again Sorry
